module.exports = {
    //POLLUX ORIGINAL
    games: [
        "p!help for commands"
        ,"p!stats for bot info"
        ,"p!invite Invite me to yout server!"
        ,"Check the most beautiful profile ever with p!profile"
        ,"Setup your Profile at www.pollux.fun/dashboard"
        ,"See commands at www.pollux.fun/commands"
        ,"Neverwinter Nights"
        ,"Warcraft III"
        ,"Play Blackjack with me! (+bj)"
        ,"Play some Slots with me! (+slots)"
        ,"Heroes of the Storm"
        ,"Pong | p!help"
        ,"The Witcher 3"
        ,"otacos na fogueira"
        ,"Fatal Frame"
        ,"Hyperdimension Neptunia"
        ,"Guild Wars 2"
        ,"EarthBound"
        ,"Elsword | p!help"
        ,"Grand Theft Auto V"
        ,"Ace Combat"
        ,"Majhong | p!help"
        ,"Starcraft II"
        ,"Lineage II"
        ,"Campo Minado"
        ,"Paciência Spider"
        ,"Imposto é Roubo!"
        ,"Bora Temer"
        ,"Lula Presidente Bolsonaro Vice"
        ,"Sudoku | p!help"
        ,"Dark Souls"
        ,"dead | p!help"
        ,"guitar | p!help"
        ,"xylophone | p!help"
        ,"Yandere Simulator"
        ,"EUROTRUCK Simulator"
        ,"Microsoft Solitaire Collection 2018 Exclusive Promo Version Czech Edition"
        ,"Faceball 2000"
        ,"Akiba Strip"
        ,"Did you know i have 5% advantage on all gambling games?"
        ,"Noticing something weird? Join my support server and let my master know!"
        ,"Fuquest"
        ,"Blackjack"
        ,"Bingo"
        ,"Jackblack"
    ]


}
