module.exports = {
    //POLLUX ORIGINAL
    games: [
        ["p!help for commands",3]
        ,["p!stats for bot info",0]
        ,["p!invite Invite me to your server!",1]
        ,["Check the most beautiful profile ever with p!profile",3]
        ,["Setup your Profile at www.pollux.fun/dashboard",2]
        ,["See commands at www.pollux.fun/commands",1]
        ,["Neverwinter Nights",0]
        ,["Warcraft III",0]
        ,["Play Blackjack with me! (+bj)",1]
        ,["Play some Slots with me! (+slots)",1]
        ,["Heroes of the Storm",0]
        ,["Pong | p!help",1]
        ,["The Witcher 3",0]
        ,["otacos na fogueira",0]
        ,["Fatal Frame",0]
        ,["Hyperdimension Neptunia",0]
        ,["Guild Wars 2",0]
        ,["EarthBound",0]
        ,["Elsword | p!help",0]
        ,["Grand Theft Auto V",0]
        ,["Ace Combat",0]
        ,["Majhong | p!help",0]
        ,["Starcraft II",0]
        ,["Technical Death Metal",2]
        ,["Lineage II",0]
        ,["Campo Minado",0]
        ,["Paciência Spider",0]
        ,["Imposto é Roubo!",3]
        ,["Bora Temer",3]
        ,["Lula Presidente Bolsonaro Vice",3]
        ,["Sudoku | p!help",0]
        ,["DARK SOULS",0]
        ,["dead | p!help",0]
        ,["guitar | p!help",0]
        ,["xylophone | p!help",0]
        ,["Yandere Simulator",0]
        ,["EUROTRUCK Simulator",0]
        ,["Microsoft Solitaire Collection 2018 Exclusive Promo Version Czech Edition",0]
        ,["Faceball 2000",0]
        ,["Akiba's Trip",0]
        ,["Did you know i have 5% advantage on all gambling games?",0]
        ,["Noticing something weird? Join my support server and let my master know!",2]
        ,["Fuquest",0]
        ,["Blackjack",0]
        ,["Bingo",0]
        ,["Jackblack",0]
        ,["YouTube Poop",3]
        ,["the world BURN",3]
        ,["complaints about blackjack being rigged",2]
        ,["the USSR National Anthem",2]
        ,["people on Deviantart",3]
        ,["dogs",3]
        ,["Bee Movie",3]
        ,["Lazy Town",3]
        ,["Japanese Jazz Fusion Mixtapes",2]
        ,["Ｖａｐｏｒｗａｖｅ",2]
        ,["Technical Death Metal",2]
        ,["ＭＡＣＩＮＴＯＳＨ　ＰＬＵＳ　－　リサフランク４２０　／　現代のコンピュー",2]
        ,["We are Number One",2]
        ,["Chip music",2]
        ,["Village People",2]
        ,["BAND MAID .tokyo",2]
        ,["your confessions",2]
        ,["Kizuna AI's Channel",3]
        ,["Th3 Bratvas Livestream",3]
        ,["out",3]
    ]


}
